# Generated by Django 5.2.5 on 2025-09-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("can_block_user", "Can block users")]},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_view_all_recipients", "Can view all recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
